/**
 * Run-time exception generated by this program
 * 
 * @author CS2334
 *
 */
public class MyRuntimeException extends RuntimeException {
	public MyRuntimeException(String message){
		super(message);
	}
}
